-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xf_cv_subtract_MatStream2AxiStream_2_s is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    imgOutput_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
    imgOutput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    imgOutput_data_empty_n : IN STD_LOGIC;
    imgOutput_data_read : OUT STD_LOGIC;
    ldata_din : OUT STD_LOGIC_VECTOR (31 downto 0);
    ldata_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
    ldata_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
    ldata_full_n : IN STD_LOGIC;
    ldata_write : OUT STD_LOGIC );
end;


architecture behav of xf_cv_subtract_MatStream2AxiStream_2_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";

attribute shreg_extract : string;
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ldata_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln1340_fu_56_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_idle : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_ready : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_imgOutput_data_read : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_din : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_write : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out_ap_vld : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_filled_1_out : STD_LOGIC_VECTOR (5 downto 0);
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_filled_1_out_ap_vld : STD_LOGIC;
    signal grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg : STD_LOGIC := '0';
    signal ap_block_state1_ignore_call5 : BOOLEAN;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_block_state3 : BOOLEAN;
    signal ldata_write_local : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_state1 : BOOLEAN;
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component xf_cv_subtract_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        imgOutput_data_dout : IN STD_LOGIC_VECTOR (23 downto 0);
        imgOutput_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgOutput_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgOutput_data_empty_n : IN STD_LOGIC;
        imgOutput_data_read : OUT STD_LOGIC;
        ldata_din : OUT STD_LOGIC_VECTOR (31 downto 0);
        ldata_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ldata_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ldata_full_n : IN STD_LOGIC;
        ldata_write : OUT STD_LOGIC;
        localbuffer_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        localbuffer_1_out_ap_vld : OUT STD_LOGIC;
        filled_1_out : OUT STD_LOGIC_VECTOR (5 downto 0);
        filled_1_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39 : component xf_cv_subtract_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start,
        ap_done => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done,
        ap_idle => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_idle,
        ap_ready => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_ready,
        imgOutput_data_dout => imgOutput_data_dout,
        imgOutput_data_num_data_valid => ap_const_lv3_0,
        imgOutput_data_fifo_cap => ap_const_lv3_0,
        imgOutput_data_empty_n => imgOutput_data_empty_n,
        imgOutput_data_read => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_imgOutput_data_read,
        ldata_din => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_din,
        ldata_num_data_valid => ap_const_lv3_0,
        ldata_fifo_cap => ap_const_lv3_0,
        ldata_full_n => ldata_full_n,
        ldata_write => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_write,
        localbuffer_1_out => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out,
        localbuffer_1_out_ap_vld => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out_ap_vld,
        filled_1_out => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_filled_1_out,
        filled_1_out_ap_vld => grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_filled_1_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_state1_ignore_call5) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_ready = ap_const_logic_1)) then 
                    grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done, ap_CS_fsm_state2, ap_block_state3, ap_block_state1)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_boolean_0 = ap_block_state1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1)
    begin
        if ((ap_const_boolean_1 = ap_block_state1)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done)
    begin
        if ((grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state3_blk_assign_proc : process(ap_block_state3)
    begin
        if ((ap_const_boolean_1 = ap_block_state3)) then 
            ap_ST_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state1_ignore_call5_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_ignore_call5 <= ((ap_start = ap_const_logic_0) or (ap_done_reg = ap_const_logic_1));
    end process;


    ap_block_state3_assign_proc : process(ldata_full_n, icmp_ln1340_fu_56_p2)
    begin
                ap_block_state3 <= ((icmp_ln1340_fu_56_p2 = ap_const_lv1_0) and (ldata_full_n = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_done_reg, ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state3, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start <= grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ap_start_reg;
    icmp_ln1340_fu_56_p2 <= "1" when (grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_filled_1_out = ap_const_lv6_0) else "0";

    imgOutput_data_read_assign_proc : process(grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_imgOutput_data_read, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            imgOutput_data_read <= grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_imgOutput_data_read;
        else 
            imgOutput_data_read <= ap_const_logic_0;
        end if; 
    end process;


    ldata_blk_n_assign_proc : process(ldata_full_n, ap_CS_fsm_state3, icmp_ln1340_fu_56_p2)
    begin
        if (((icmp_ln1340_fu_56_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ldata_blk_n <= ldata_full_n;
        else 
            ldata_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    ldata_din_assign_proc : process(grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_din, grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out, ap_CS_fsm_state2)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ldata_din <= grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_din;
        else 
            ldata_din <= grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_localbuffer_1_out;
        end if; 
    end process;


    ldata_write_assign_proc : process(grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_write, ap_CS_fsm_state2, ldata_write_local)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state2)) then 
            ldata_write <= grp_MatStream2AxiStream_2_Pipeline_MMIterOutRow_MMIterOutCol_fu_39_ldata_write;
        else 
            ldata_write <= ldata_write_local;
        end if; 
    end process;


    ldata_write_local_assign_proc : process(ap_CS_fsm_state3, icmp_ln1340_fu_56_p2, ap_block_state3)
    begin
        if (((ap_const_boolean_0 = ap_block_state3) and (icmp_ln1340_fu_56_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
            ldata_write_local <= ap_const_logic_1;
        else 
            ldata_write_local <= ap_const_logic_0;
        end if; 
    end process;

end behav;
