// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module xf_cv_subtract_subtract_0_16_1920_1080_1_2_2_2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        imgInput1_data_dout,
        imgInput1_data_num_data_valid,
        imgInput1_data_fifo_cap,
        imgInput1_data_empty_n,
        imgInput1_data_read,
        imgInput2_data_dout,
        imgInput2_data_num_data_valid,
        imgInput2_data_fifo_cap,
        imgInput2_data_empty_n,
        imgInput2_data_read,
        imgOutput_data_din,
        imgOutput_data_num_data_valid,
        imgOutput_data_fifo_cap,
        imgOutput_data_full_n,
        imgOutput_data_write
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [23:0] imgInput1_data_dout;
input  [2:0] imgInput1_data_num_data_valid;
input  [2:0] imgInput1_data_fifo_cap;
input   imgInput1_data_empty_n;
output   imgInput1_data_read;
input  [23:0] imgInput2_data_dout;
input  [2:0] imgInput2_data_num_data_valid;
input  [2:0] imgInput2_data_fifo_cap;
input   imgInput2_data_empty_n;
output   imgInput2_data_read;
output  [23:0] imgOutput_data_din;
input  [2:0] imgOutput_data_num_data_valid;
input  [2:0] imgOutput_data_fifo_cap;
input   imgOutput_data_full_n;
output   imgOutput_data_write;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg imgInput1_data_read;
reg imgInput2_data_read;
reg imgOutput_data_write;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_done;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_idle;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_ready;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput1_data_read;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput2_data_read;
wire   [23:0] grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_din;
wire    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_write;
reg    grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln820_fu_58_p2;
wire    ap_CS_fsm_state3;
reg   [10:0] i_fu_36;
wire   [10:0] i_2_fu_64_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg = 1'b0;
#0 i_fu_36 = 11'd0;
end

xf_cv_subtract_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start),
    .ap_done(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_done),
    .ap_idle(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_idle),
    .ap_ready(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_ready),
    .imgInput1_data_dout(imgInput1_data_dout),
    .imgInput1_data_num_data_valid(3'd0),
    .imgInput1_data_fifo_cap(3'd0),
    .imgInput1_data_empty_n(imgInput1_data_empty_n),
    .imgInput1_data_read(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput1_data_read),
    .imgInput2_data_dout(imgInput2_data_dout),
    .imgInput2_data_num_data_valid(3'd0),
    .imgInput2_data_fifo_cap(3'd0),
    .imgInput2_data_empty_n(imgInput2_data_empty_n),
    .imgInput2_data_read(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput2_data_read),
    .imgOutput_data_din(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_din),
    .imgOutput_data_num_data_valid(3'd0),
    .imgOutput_data_fifo_cap(3'd0),
    .imgOutput_data_full_n(imgOutput_data_full_n),
    .imgOutput_data_write(grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_write)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln820_fu_58_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln820_fu_58_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg <= 1'b1;
        end else if ((grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_ready == 1'b1)) begin
            grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
        i_fu_36 <= 11'd0;
    end else if (((icmp_ln820_fu_58_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_fu_36 <= i_2_fu_64_p2;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln820_fu_58_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln820_fu_58_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgInput1_data_read = grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput1_data_read;
    end else begin
        imgInput1_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgInput2_data_read = grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgInput2_data_read;
    end else begin
        imgInput2_data_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        imgOutput_data_write = grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_write;
    end else begin
        imgOutput_data_write = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b0 == ap_block_state1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln820_fu_58_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start = grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_ap_start_reg;

assign i_2_fu_64_p2 = (i_fu_36 + 11'd1);

assign icmp_ln820_fu_58_p2 = ((i_fu_36 == 11'd1920) ? 1'b1 : 1'b0);

assign imgOutput_data_din = grp_subtract_0_16_1920_1080_1_2_2_2_Pipeline_colLoop_fu_40_imgOutput_data_din;

endmodule //xf_cv_subtract_subtract_0_16_1920_1080_1_2_2_2_s
