# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.srcs/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0.xci
# IP: The module: 'camera_design_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.srcs/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0.xci
# IP: The module: 'camera_design_axi_iic_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: d:/design_project-code/SmartSentry2/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_axi_iic_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
