# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/camera_design/camera_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design || ORIG_REF_NAME==camera_design} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_processing_system7_0_0 || ORIG_REF_NAME==camera_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_proc_sys_reset_0_0/camera_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_proc_sys_reset_0_0 || ORIG_REF_NAME==camera_design_proc_sys_reset_0_0} -quiet] -quiet

# XDC: c:/Users/georg/Documents/UWaterloo/4A/FYDP/camera_repo/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/camera_design_ooc.xdc
