# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pynq_z2_constraints.xdc

# Block Designs: bd/camera_design/camera_design.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design || ORIG_REF_NAME==camera_design} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_processing_system7_0_0 || ORIG_REF_NAME==camera_design_processing_system7_0_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_proc_sys_reset_0_0/camera_design_proc_sys_reset_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_proc_sys_reset_0_0 || ORIG_REF_NAME==camera_design_proc_sys_reset_0_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_axi_iic_0_0/camera_design_axi_iic_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_axi_iic_0_0 || ORIG_REF_NAME==camera_design_axi_iic_0_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_xbar_0/camera_design_xbar_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_xbar_0 || ORIG_REF_NAME==camera_design_xbar_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_ps7_0_axi_periph_0/camera_design_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_ps7_0_axi_periph_0 || ORIG_REF_NAME==camera_design_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_axi_quad_spi_0_0/camera_design_axi_quad_spi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_axi_quad_spi_0_0 || ORIG_REF_NAME==camera_design_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/camera_design/ip/camera_design_auto_pc_0/camera_design_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==camera_design_auto_pc_0 || ORIG_REF_NAME==camera_design_auto_pc_0} -quiet] -quiet

# XDC: c:/Users/georg/vitis/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/camera_design_ooc.xdc
