// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module xf_cv_subtract_AxiStream2Mat (
        ldata_dout,
        ldata_empty_n,
        ldata_read,
        imgInput1_data_din,
        imgInput1_data_full_n,
        imgInput1_data_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [31:0] ldata_dout;
input   ldata_empty_n;
output   ldata_read;
output  [23:0] imgInput1_data_din;
input   imgInput1_data_full_n;
output   imgInput1_data_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    AxiStream2MatStream_2_U0_ap_start;
wire    AxiStream2MatStream_2_U0_ap_done;
wire    AxiStream2MatStream_2_U0_ap_continue;
wire    AxiStream2MatStream_2_U0_ap_idle;
wire    AxiStream2MatStream_2_U0_ap_ready;
wire    AxiStream2MatStream_2_U0_ldata_read;
wire   [23:0] AxiStream2MatStream_2_U0_imgInput1_data_din;
wire    AxiStream2MatStream_2_U0_imgInput1_data_write;

xf_cv_subtract_AxiStream2MatStream_2_s AxiStream2MatStream_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(AxiStream2MatStream_2_U0_ap_start),
    .ap_done(AxiStream2MatStream_2_U0_ap_done),
    .ap_continue(AxiStream2MatStream_2_U0_ap_continue),
    .ap_idle(AxiStream2MatStream_2_U0_ap_idle),
    .ap_ready(AxiStream2MatStream_2_U0_ap_ready),
    .ldata_dout(ldata_dout),
    .ldata_num_data_valid(3'd0),
    .ldata_fifo_cap(3'd0),
    .ldata_empty_n(ldata_empty_n),
    .ldata_read(AxiStream2MatStream_2_U0_ldata_read),
    .imgInput1_data_din(AxiStream2MatStream_2_U0_imgInput1_data_din),
    .imgInput1_data_num_data_valid(3'd0),
    .imgInput1_data_fifo_cap(3'd0),
    .imgInput1_data_full_n(imgInput1_data_full_n),
    .imgInput1_data_write(AxiStream2MatStream_2_U0_imgInput1_data_write)
);

assign AxiStream2MatStream_2_U0_ap_continue = ap_continue;

assign AxiStream2MatStream_2_U0_ap_start = ap_start;

assign ap_done = AxiStream2MatStream_2_U0_ap_done;

assign ap_idle = AxiStream2MatStream_2_U0_ap_idle;

assign ap_ready = AxiStream2MatStream_2_U0_ap_ready;

assign imgInput1_data_din = AxiStream2MatStream_2_U0_imgInput1_data_din;

assign imgInput1_data_write = AxiStream2MatStream_2_U0_imgInput1_data_write;

assign ldata_read = AxiStream2MatStream_2_U0_ldata_read;

endmodule //xf_cv_subtract_AxiStream2Mat
