domain_path: C:\Users\georg\vitis_workspace\nand_tutorial_platform\export\nand_tutorial_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: C:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\hello_world
template: hello_world
