domain_path: d:\design_project-code\SmartSentry\camera_fw\vitis\camera_platform\export\camera_platform\sw\standalone_ps7_cortexa9_0
app_src_dir: D:\Xilinx\Vitis\2024.1\data\embeddedsw\lib\sw_apps\lwip_echo_server
template: lwip_echo_server
