# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/georg/Documents/UWaterloo/4A/FYDP/camera_repo/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.srcs/sources_1/bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xci
# IP: The module: 'camera_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georg/Documents/UWaterloo/4A/FYDP/camera_repo/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: c:/Users/georg/Documents/UWaterloo/4A/FYDP/camera_repo/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.srcs/sources_1/bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xci
# IP: The module: 'camera_design_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/georg/Documents/UWaterloo/4A/FYDP/camera_repo/SmartSentry/camera_fw/vivado/camera_hw/camera_hw.gen/sources_1/bd/camera_design/ip/camera_design_processing_system7_0_0/camera_design_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'camera_design_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
