-- ==============================================================
-- Generated by Vitis HLS v2024.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity xf_cv_subtract_AxiStream2Mat is
port (
    ldata_dout : IN STD_LOGIC_VECTOR (31 downto 0);
    ldata_empty_n : IN STD_LOGIC;
    ldata_read : OUT STD_LOGIC;
    imgInput1_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
    imgInput1_data_full_n : IN STD_LOGIC;
    imgInput1_data_write : OUT STD_LOGIC;
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC );
end;


architecture behav of xf_cv_subtract_AxiStream2Mat is 
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal AxiStream2MatStream_2_U0_ap_start : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_ap_done : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_ap_continue : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_ap_idle : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_ap_ready : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_ldata_read : STD_LOGIC;
    signal AxiStream2MatStream_2_U0_imgInput1_data_din : STD_LOGIC_VECTOR (23 downto 0);
    signal AxiStream2MatStream_2_U0_imgInput1_data_write : STD_LOGIC;

    component xf_cv_subtract_AxiStream2MatStream_2_s IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ldata_dout : IN STD_LOGIC_VECTOR (31 downto 0);
        ldata_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        ldata_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        ldata_empty_n : IN STD_LOGIC;
        ldata_read : OUT STD_LOGIC;
        imgInput1_data_din : OUT STD_LOGIC_VECTOR (23 downto 0);
        imgInput1_data_num_data_valid : IN STD_LOGIC_VECTOR (2 downto 0);
        imgInput1_data_fifo_cap : IN STD_LOGIC_VECTOR (2 downto 0);
        imgInput1_data_full_n : IN STD_LOGIC;
        imgInput1_data_write : OUT STD_LOGIC );
    end component;



begin
    AxiStream2MatStream_2_U0 : component xf_cv_subtract_AxiStream2MatStream_2_s
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => AxiStream2MatStream_2_U0_ap_start,
        ap_done => AxiStream2MatStream_2_U0_ap_done,
        ap_continue => AxiStream2MatStream_2_U0_ap_continue,
        ap_idle => AxiStream2MatStream_2_U0_ap_idle,
        ap_ready => AxiStream2MatStream_2_U0_ap_ready,
        ldata_dout => ldata_dout,
        ldata_num_data_valid => ap_const_lv3_0,
        ldata_fifo_cap => ap_const_lv3_0,
        ldata_empty_n => ldata_empty_n,
        ldata_read => AxiStream2MatStream_2_U0_ldata_read,
        imgInput1_data_din => AxiStream2MatStream_2_U0_imgInput1_data_din,
        imgInput1_data_num_data_valid => ap_const_lv3_0,
        imgInput1_data_fifo_cap => ap_const_lv3_0,
        imgInput1_data_full_n => imgInput1_data_full_n,
        imgInput1_data_write => AxiStream2MatStream_2_U0_imgInput1_data_write);




    AxiStream2MatStream_2_U0_ap_continue <= ap_continue;
    AxiStream2MatStream_2_U0_ap_start <= ap_start;
    ap_done <= AxiStream2MatStream_2_U0_ap_done;
    ap_idle <= AxiStream2MatStream_2_U0_ap_idle;
    ap_ready <= AxiStream2MatStream_2_U0_ap_ready;
    imgInput1_data_din <= AxiStream2MatStream_2_U0_imgInput1_data_din;
    imgInput1_data_write <= AxiStream2MatStream_2_U0_imgInput1_data_write;
    ldata_read <= AxiStream2MatStream_2_U0_ldata_read;
end behav;
