// ==============================================================
// Generated by Vitis HLS v2024.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module xf_cv_subtract_Mat2AxiStream (
        imgOutput_data_dout,
        imgOutput_data_empty_n,
        imgOutput_data_read,
        ldata_din,
        ldata_full_n,
        ldata_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [23:0] imgOutput_data_dout;
input   imgOutput_data_empty_n;
output   imgOutput_data_read;
output  [31:0] ldata_din;
input   ldata_full_n;
output   ldata_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    MatStream2AxiStream_2_U0_ap_start;
wire    MatStream2AxiStream_2_U0_ap_done;
wire    MatStream2AxiStream_2_U0_ap_continue;
wire    MatStream2AxiStream_2_U0_ap_idle;
wire    MatStream2AxiStream_2_U0_ap_ready;
wire    MatStream2AxiStream_2_U0_imgOutput_data_read;
wire   [31:0] MatStream2AxiStream_2_U0_ldata_din;
wire    MatStream2AxiStream_2_U0_ldata_write;

xf_cv_subtract_MatStream2AxiStream_2_s MatStream2AxiStream_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(MatStream2AxiStream_2_U0_ap_start),
    .ap_done(MatStream2AxiStream_2_U0_ap_done),
    .ap_continue(MatStream2AxiStream_2_U0_ap_continue),
    .ap_idle(MatStream2AxiStream_2_U0_ap_idle),
    .ap_ready(MatStream2AxiStream_2_U0_ap_ready),
    .imgOutput_data_dout(imgOutput_data_dout),
    .imgOutput_data_num_data_valid(3'd0),
    .imgOutput_data_fifo_cap(3'd0),
    .imgOutput_data_empty_n(imgOutput_data_empty_n),
    .imgOutput_data_read(MatStream2AxiStream_2_U0_imgOutput_data_read),
    .ldata_din(MatStream2AxiStream_2_U0_ldata_din),
    .ldata_num_data_valid(3'd0),
    .ldata_fifo_cap(3'd0),
    .ldata_full_n(ldata_full_n),
    .ldata_write(MatStream2AxiStream_2_U0_ldata_write)
);

assign MatStream2AxiStream_2_U0_ap_continue = ap_continue;

assign MatStream2AxiStream_2_U0_ap_start = ap_start;

assign ap_done = MatStream2AxiStream_2_U0_ap_done;

assign ap_idle = MatStream2AxiStream_2_U0_ap_idle;

assign ap_ready = MatStream2AxiStream_2_U0_ap_ready;

assign imgOutput_data_read = MatStream2AxiStream_2_U0_imgOutput_data_read;

assign ldata_din = MatStream2AxiStream_2_U0_ldata_din;

assign ldata_write = MatStream2AxiStream_2_U0_ldata_write;

endmodule //xf_cv_subtract_Mat2AxiStream
